# Generated by Django 4.1.2 on 2022-10-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("city", models.CharField(max_length=100, null=True)),
                ("date", models.DateTimeField(max_length=100, null=True)),
                ("team1", models.CharField(max_length=100, null=True)),
                ("team2", models.CharField(max_length=100, null=True)),
                ("toss_winner", models.CharField(max_length=100, null=True)),
                ("toss_decision", models.CharField(max_length=100, null=True)),
                ("result", models.CharField(max_length=100, null=True)),
                ("dl_applied", models.BooleanField()),
                ("winner", models.CharField(max_length=100, null=True)),
                ("win_by_runs", models.IntegerField()),
                ("win_by_wickets", models.IntegerField()),
                ("player_of_match", models.CharField(max_length=100, null=True)),
                ("venue", models.CharField(max_length=100, null=True)),
                ("umpire1", models.CharField(max_length=100, null=True)),
                ("umpire2", models.CharField(max_length=100, null=True)),
                ("umpire3", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Native",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DATE", models.DateTimeField(max_length=300, null=True)),
                ("PCC_SITENAME", models.CharField(max_length=300, null=True)),
                ("PCC_AUDIENCE", models.CharField(max_length=300, null=True)),
                ("PCC_UNIT_TYPE", models.CharField(max_length=300, null=True)),
                ("PCC_PLATFORM_DEVICE", models.CharField(max_length=300, null=True)),
                ("CREATIVE_NAME", models.CharField(max_length=300, null=True)),
                ("CREATIVE_TYPE", models.CharField(max_length=300, null=True)),
                ("CREATIVE_PLACEMENT", models.CharField(max_length=300, null=True)),
                ("CAMPAIGN_GROUP", models.CharField(max_length=300, null=True)),
                ("HEADLINE", models.CharField(max_length=300, null=True)),
                ("BODY", models.CharField(max_length=300, null=True)),
                ("COST", models.FloatField(null=True)),
                ("CLICKS", models.IntegerField(null=True)),
                ("IMPRESSIONS", models.IntegerField(null=True)),
                ("ENGAGEMENTS", models.IntegerField(null=True)),
                ("LIKES", models.IntegerField(null=True)),
                ("SHARES", models.IntegerField(null=True)),
                ("LEADS", models.IntegerField(null=True)),
                ("FOLLOWS", models.IntegerField(null=True)),
                ("COMMENTS", models.IntegerField(null=True)),
                ("REACTIONS", models.IntegerField(null=True)),
                ("LANDING_PAGE_CLICKS", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.IntegerField()),
                ("batting_team", models.CharField(max_length=100, null=True)),
                ("bowling_team", models.CharField(max_length=100, null=True)),
                ("over", models.IntegerField()),
                ("ball", models.IntegerField()),
                ("batsman", models.CharField(max_length=100, null=True)),
                ("non_striker", models.CharField(max_length=100, null=True)),
                ("bowler", models.CharField(max_length=100, null=True)),
                ("is_super_over", models.BooleanField()),
                ("wide_runs", models.IntegerField()),
                ("bye_runs", models.IntegerField()),
                ("legbye_runs", models.IntegerField()),
                ("noball_runs", models.IntegerField()),
                ("penalty_runs", models.IntegerField()),
                ("batsman_runs", models.IntegerField()),
                ("extra_runs", models.IntegerField()),
                ("total_runs", models.IntegerField()),
                ("player_dismissed", models.CharField(max_length=100, null=True)),
                ("dismissal_kind", models.CharField(max_length=100, null=True)),
                ("fielder", models.CharField(max_length=100, null=True)),
                (
                    "match_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.matches",
                    ),
                ),
            ],
        ),
    ]
