# Generated by Django 4.1.2 on 2022-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveries",
            name="batsman",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="batting_team",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="bowler",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="bowling_team",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="dismissal_kind",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="fielder",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="non_striker",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="player_dismissed",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="date",
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="player_of_match",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="result",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="team1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="team2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="toss_decision",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="toss_winner",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="umpire1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="umpire2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="venue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matches",
            name="winner",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
