# Generated by Django 4.1.2 on 2022-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_deliveries_batsman_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="umpire3",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
