# Generated by Django 4.1.2 on 2022-10-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_alter_matches_umpire3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveries",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="deliveries",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="matches",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="matches",
            name="updated_at",
        ),
    ]
